[project]
name = "htpy-htmx"
version = "0.1.0"
authors = [ { name = "August Malmdahl" } ]
description = "Helpers for using htmx in htpy"
requires-python = ">=3.10"
readme = "README.md"
dependencies = [
    "htpy",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Typing :: Typed",
]


[dependency-groups]
dev = [
    "black>=26.5.1",
    "mypy>=2.3.0",
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
]


[tool.black]
line-length = 100
target-version = ['py310']
include = '\.pyi?$'


[tool.mypy]
strict = true
exclude = "build"


[tool.pytest.ini_options]
python_files="tests/**.py"
norecursedirs=".*"


[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"
packages = ["htpy_htmx"]
